---
title: "BIENVENIDOS"

---

# Visión general

Este sitio web es el punto de partida para una secuencia de clases de reforzamiento del curso **"Computación y programación Básica - 2do Semestre 2021"** realizado por la Universidad de Concepción.

Este es un curso que forma parte del programa de capacitaciones y entrenamiento de **The Nature Conservancy Perú** en Análisis de datos con R. 

# Clases Online

Favor de unirse a Microsoft Teams todos los lunes de 15:15 a 17:00.

La primera media hora se procederá a realizar consultas/repaso del material previamente asignado en clases por los profesores principales del curso: Dr. Billy Ernst y el Dr. Diego Narváez. Posteriormente se le asignará un test de 30 minutos de duración el cual deberá ser resuelto en canvas. El solucionario del test y/o consultas, comentarios del mismo se realizará en la última media hora.

# Temario

1. Septiembre 6: **R-project**\
Familiarizarse con los conceptos generales del software R-project y el entorno de desarrollo R-Studio.\
[Semana 1 y 2](./rstudio.html)

2. Septiembre 13: **Datos**\
Familiarizarse con los tipos de datos en R, matrices, vectores, dataframes, importación de archivos. Operaciones matriciales y por elementos. Uso y operaciones con dataframes. La temática del tópico **Datos** se dividirá en tres semanas, en las cuales se abordarán los siguientes puntos:

    - Variables en R, input/output \
    [Semana 3](./datos.html)
    
    - Operaciones matriciales y por elemento \
    [Semana 4](./datos.html)
    
    - Uso y operaciones con dataframe \
    [Semana 5](./datos.html)

3. Octubre 4: **Programación**. Conocer los principales comandos en la programación en R. Desarrollar diagramas de flujos. Crear algoritmos y desarrollar opciones avanzadas de manipulación de dataframes. Este tópico se sub-dividirá en 3 semana donde se abordarán los siguientes puntos:

    - Operadores aritméticos y lógicos. Diagramas de flujo 
    
    - Condicionales \
    [Semana 7](./condicionales.html)
    
    - Ciclos o bucles \
    [Semana 8](./condicionales.html)
    
4. Octubre 25: **Funciones**. Implementar funciones personalizadas para desarrollar tareas específicas. Emplear funciones gráficas para la visualización de datos. Este tópico se sub-dividirá en 3 semanas donde se abordarán los siguientes puntos:

    - Funciones en R. 
    
    - Funciones gráficas I y II \
    [Semana 9](./graficos.html)

5. Noviembre: **Aplicaciones**. Desarrollar una función con aplicación biológicas. Trabajo final.





